services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    volumes:
      - cache:/data
volumes:
  cache:
